name: 2Players
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.8=h166bdaf_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - attr=2.5.1=h166bdaf_1
  - attrs=23.2.0=pyh71513ae_0
  - blas=1.0=mkl
  - blosc=1.21.5=hc2324a3_1
  - boost-cpp=1.78.0=h5adbc97_2
  - bottleneck=1.3.7=py39ha9d4c09_0
  - branca=0.7.2=pyhd8ed1ab_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py39h5a03fae_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.28.1=hd590300_0
  - ca-certificates=2024.6.2=hbcca054_0
  - cairo=1.16.0=ha61ee94_1014
  - certifi=2024.6.2=pyhd8ed1ab_0
  - cfitsio=4.2.0=hd9d235c_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.0=py39hdb19cb5_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.5.39=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.5=3
  - curl=8.1.2=h409715c_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py39h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.2=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - fftw=3.3.10=nompi_hf0379b8_106
  - filelock=3.14.0=pyhd8ed1ab_0
  - folium=0.16.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.51.0=py39h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - freexl=1.0.6=h166bdaf_1
  - gdal=3.5.3=py39h5cb30a4_5
  - geopandas=0.14.4=pyhd8ed1ab_0
  - geopandas-base=0.14.4=pyha770c72_0
  - geos=3.11.1=h27087fc_0
  - geotiff=1.7.1=ha76d385_4
  - gettext=0.22.5=h59595ed_2
  - gettext-tools=0.22.5=h59595ed_2
  - giflib=5.2.2=hd590300_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.3.0=h59595ed_1
  - gnutls=3.6.13=h85f3911_1
  - graphite2=1.3.13=h59595ed_1003
  - gst-plugins-base=1.22.0=h4243ec0_2
  - gstreamer=1.22.0=h25f0c4b_2
  - gstreamer-orc=0.4.38=hd590300_0
  - harfbuzz=6.0.0=h8e241bc_0
  - hdf4=4.2.15=h9772cbc_5
  - hdf5=1.12.2=nompi_h4df4325_101
  - icu=70.1=h27087fc_0
  - idna=3.7=pyhd8ed1ab_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - importlib_resources=6.1.1=py39h06a4308_1
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.3=pyhd33586a_0
  - ipython=8.18.1=pyh707e725_3
  - jack=1.9.22=h11f4161_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_1
  - json-c=0.16=hc379101_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py39hf3d152e_0
  - kealib=1.5.0=ha7026e8_0
  - kiwisolver=1.4.4=py39h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h166bdaf_1003
  - lcms2=2.14=h6ed2654_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libaec=1.1.3=h59595ed_0
  - libasprintf=0.22.5=h661eb56_2
  - libasprintf-devel=0.22.5=h661eb56_2
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libcap=2.67=he9d0100_0
  - libclang=15.0.7=default_h127d8a8_5
  - libclang13=15.0.7=default_h5d6823c_5
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.10.0.4=0
  - libcups=2.3.3=h36d4200_3
  - libcurand=10.3.6.39=0
  - libcurl=8.1.2=h409715c_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdap4=3.20.6=hd7c4107_2
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.12=h166bdaf_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=hd590300_2
  - libevent=2.1.10=h28343ad_4
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.4.3=h59595ed_0
  - libgcc-ng=13.2.0=h77fa898_7
  - libgcrypt=1.10.3=hd590300_0
  - libgdal=3.5.3=h7516191_5
  - libgettextpo=0.22.5=h59595ed_2
  - libgettextpo-devel=0.22.5=h59595ed_2
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=13.2.0=h77fa898_7
  - libgpg-error=1.49=h4f305b6_0
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libkml=1.3.0=h01aab08_1016
  - libllvm14=14.0.6=hdb19cb5_3
  - libllvm15=15.0.7=hadd5161_1
  - libnetcdf=4.8.1=nompi_h261ec11_106
  - libnghttp2=1.58.0=h47da74e_0
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libogg=1.3.4=h7f98852_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h5eee18b_0
  - libpq=15.2=hb675445_0
  - librttopo=1.1.0=ha49c73b_12
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.18=h36c2ea0_1
  - libspatialindex=1.9.3=he02047a_5
  - libspatialite=5.0.1=h7c8129e_22
  - libsqlite=3.45.3=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=hc0a3c3a_7
  - libsystemd0=253=h8c4010b_1
  - libtiff=4.4.0=hc85c160_1
  - libtool=2.4.7=h27087fc_0
  - libudev1=253=h0b41bf4_1
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.5.0=h79f4944_1
  - libxml2=2.10.3=hca2bb57_4
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=15.0.7=h0cdce71_0
  - lz4-c=1.9.4=h6a678d5_1
  - mapclassify=2.6.1=pyhd8ed1ab_0
  - markupsafe=2.1.5=py39hd1e30aa_0
  - matplotlib=3.8.4=py39h06a4308_0
  - matplotlib-base=3.8.4=py39h1128e8f_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.8=py39h5eee18b_0
  - mkl_random=1.2.4=py39hdb19cb5_0
  - mpg123=1.32.6=h59595ed_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - munch=4.0.0=pyhd8ed1ab_0
  - mysql=5.7.24=h721c034_2
  - mysql-common=8.0.33=hf1915f5_6
  - mysql-libs=8.0.33=hca2cd23_6
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.6=he412f7d_0
  - networkx=3.2.1=pyhd8ed1ab_0
  - nspr=4.35=h27087fc_0
  - nss=3.100=hca3bf56_0
  - numexpr=2.8.7=py39h85018f9_0
  - numpy=1.26.4=py39h5f9d8c6_0
  - numpy-base=1.26.4=py39hb5e798b_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=h7d73246_1
  - openssl=3.1.6=h4ab18f5_0
  - packaging=23.2=py39h06a4308_0
  - pandas=2.2.1=py39h6a678d5_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.3.0=py39h5eee18b_0
  - pip=24.0=py39h06a4308_0
  - pixman=0.43.2=h59595ed_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - ply=3.11=py39h06a4308_0
  - poppler=22.11.0=h92391eb_0
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=15.2=h3248436_0
  - proj=9.1.0=h93bde94_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.8=py39hd1e30aa_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulseaudio=16.1=hcb278e6_3
  - pulseaudio-client=16.1=h5195f5e_3
  - pulseaudio-daemon=16.1=ha8d29e2_3
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pybind11-abi=4=hd3eb1b0_1
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=py39h06a4308_0
  - pyqt=5.15.10=py39h6a678d5_0
  - pyqt5-sip=12.13.0=py39h5eee18b_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.19=h955ad1f_1
  - python-dateutil=2.9.0post0=py39h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch=2.3.1=py3.9_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py39h06a4308_0
  - pyyaml=6.0.1=py39hd1e30aa_1
  - pyzmq=25.1.2=py39h6a678d5_0
  - qt-main=5.15.8=h5d23da1_6
  - readline=8.2=h5eee18b_0
  - requests=2.32.2=pyhd8ed1ab_0
  - rtree=1.2.0=py39hb102c33_0
  - scikit-learn=1.5.0=py39h40c85ba_1
  - scipy=1.13.0=py39h5f9d8c6_0
  - setuptools=69.5.1=py39h06a4308_0
  - sip=6.7.12=py39h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.0=hdb0a2a9_1
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.12=pyh04b8f61_3
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tiledb=2.11.3=h3f4058f_1
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.1=py39h06a4308_0
  - torchaudio=2.3.1=py39_cu121
  - torchtriton=2.3.1=py39
  - torchvision=0.18.1=py39_cu121
  - tornado=6.3.3=py39h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - tzcode=2024a=h3f72095_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py39h5eee18b_0
  - uriparser=0.9.8=hac33072_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=py39h06a4308_0
  - xcb-util=0.4.0=h516909a_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h516909a_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h516909a_0
  - xerces-c=3.2.4=h55805fa_1
  - xkeyboard-config=2.38=h0b41bf4_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.17.0=py39h06a4308_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hc292b87_2
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - aenum==3.1.15
      - affine==2.4.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - albucore==0.0.24
      - albumentations==2.0.8
      - aniso8601==9.0.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.4.0
      - anywidget==0.9.13
      - async-timeout==4.0.3
      - beautifulsoup4==4.12.3
      - bitsandbytes==0.41.0
      - blinker==1.8.2
      - bqplot==0.12.43
      - cachelib==0.9.0
      - cachetools==5.4.0
      - color-operations==0.1.5
      - colour==0.1.5
      - datasets==4.1.1
      - dill==0.4.0
      - distinctipy==1.3.4
      - docstring-parser==0.16
      - duckdb==1.0.0
      - efficientnet-pytorch==0.7.1
      - einops==0.8.0
      - eval-type-backport==0.2.2
      - ever-beta==0.5.3
      - fiona==1.9.6
      - flask==3.0.3
      - flask-caching==2.3.0
      - flask-cors==4.0.1
      - flask-restx==1.3.0
      - frozenlist==1.4.1
      - fsspec==2024.6.0
      - gdown==5.2.0
      - geojson==3.1.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - groundingdino-py==0.4.0
      - grpcio==1.64.1
      - h11==0.14.0
      - h5py==3.11.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.24.0
      - hydra-core==1.3.2
      - ignite==1.1.0
      - imageio==2.34.2
      - ipyevents==2.0.2
      - ipyfilechooser==0.6.0
      - ipyleaflet==0.19.2
      - ipytree==0.2.2
      - ipyvue==1.11.1
      - ipyvuetify==1.10.0
      - ipywidgets==8.1.3
      - itsdangerous==2.2.0
      - jsonargparse==4.36.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-leaflet==0.19.2
      - jupyterlab-widgets==3.0.11
      - kornia==0.7.2
      - kornia-rs==0.1.3
      - lazy-loader==0.4
      - leafmap==0.36.6
      - lightly==1.5.17
      - lightly-utils==0.0.2
      - lightning==2.2.5
      - lightning-utilities==0.11.2
      - localtileserver==0.10.3
      - markdown==3.6
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - morecantile==5.3.1
      - multidict==6.0.5
      - multiprocess==0.70.16
      - omegaconf==2.3.0
      - opencv-python==4.10.0.82
      - opencv-python-headless==4.10.0.84
      - patchify==0.2.3
      - patool==1.15.0
      - plotly==5.23.0
      - pretrainedmodels==0.7.4
      - prettytable==3.16.0
      - protobuf==4.25.3
      - psygnal==0.11.1
      - pyarrow==21.0.0
      - pycocotools==2.0.8
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pyogrio==0.8.0
      - pyproj==3.6.1
      - pyshp==2.3.1
      - pystac==1.10.1
      - pystac-client==0.8.3
      - python-box==7.2.0
      - pytorch-ignite==0.5.0.post2
      - pytorch-lightning==2.2.5
      - pytorch-lightning-bolts==0.3.2.post1
      - rasterio==1.3.10
      - referencing==0.35.1
      - regex==2024.7.24
      - rich==13.9.4
      - rio-cogeo==5.3.3
      - rio-tiler==6.6.1
      - rpds-py==0.20.0
      - safetensors==0.4.3
      - scikit-image==0.24.0
      - scooby==0.10.0
      - seaborn==0.13.2
      - segment-anything-hq==0.3
      - segment-anything-py==1.0.1
      - segment-geospatial==0.10.6
      - segmentation-models-pytorch==0.4.0
      - sentry-sdk==2.38.0
      - server-thread==0.2.0
      - shapely==2.0.4
      - simsimd==6.5.3
      - smmap==5.0.2
      - sniffio==1.3.1
      - snuggs==1.4.7
      - soupsieve==2.5
      - stringzilla==4.0.13
      - supervision==0.6.0
      - tenacity==9.0.0
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tifffile==2024.6.18
      - timm==1.0.7
      - tokenizers==0.19.1
      - torchange==0.0.2
      - torchgeo==0.5.2
      - torchinfo==1.8.0
      - torchmetrics==1.4.0.post0
      - tqdm==4.66.4
      - traittypes==0.2.1
      - transformers==4.44.2
      - typeshed-client==2.7.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - uvicorn==0.30.6
      - wandb==0.22.0
      - werkzeug==3.0.3
      - whitebox==2.3.5
      - whiteboxgui==2.3.0
      - widgetsnbextension==4.0.11
      - wrapt==1.16.0
      - xarray==2024.7.0
      - xxhash==3.5.0
      - xyzservices==2024.6.0
      - yapf==0.40.2
      - yarl==1.9.4
prefix: /home/manon/miniconda3/envs/2Players
